services:
  main:
    image: mcr.microsoft.com/devcontainers/javascript-node:22-bookworm
    volumes:
      - ..:/workspace:cached
      - ./main/root/.zsh_history:/root/.zsh_history
      - ./main/root/.zshrc:/root/.zshrc
      - main-pnpm-store:/workspace/.pnpm-store
    command: sleep infinity
    networks:
      - main-net

volumes:
  main-pnpm-store:

networks:
  main-net:
